name: Java/Docker/Kubernetes CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Maven Build
      uses: ./actions/build
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }} 
        GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}  
    - name: Docker Build and Push
      uses: ./actions/docker-push
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: Update EKS
      uses: ./actions/deploy-eks
      with:
        args: apply -f deployment-java-hello-world.yaml
      env:
        KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}